### ISSUE TITLE
第二章EX1笔误

### ISSUE THREAD

**Issue by Picky02-ji** [furtherun/Introductory-Combinatorics-5ed#2]
错误处：当条件a和条件b都不满足时，每一位都可以取任意数，共4^5种。

**Comment by furtherun** [comment]
你说的对，已经纠正，感谢指出。👍

**Comment by furtherun** [comment]
[以此为准](https://github.com/furtherun/Introductory-Combinatorics-5ed/issues/13#issuecomment-3714744278)。
